spring.application.name=dssd
spring.datasource.url=jdbc:postgresql://localhost:5432/dssd_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.hibernate.ddl-auto=update

# Configuracion de Bonita
bonita.api.url=http://localhost:52365/bonita
bonita.api.base-url=http://localhost:52365/bonita
bonita.api.username=walter.bates
bonita.api.password=bpm
bonita.api.process-name=GestionEmergencias
bonita.process.name=GestionEmergencias